;===============================================================================
; Environments
;===============================================================================

[dev]
kara

[prod]
seven


;===============================================================================
; Web hosts
;===============================================================================

[hetzner]
seven

[home]
kara


;===============================================================================
; Primary user accounts
;===============================================================================
; This determines which user is created initially and used for SSH connections
; - Amazon EC2 and Multipass use 'ubuntu'
; - Hetzner uses 'root'

[primary_user_root]
seven

[primary_user_ubuntu]
kara
