;===============================================================================
; Environments
;===============================================================================

[dev]
kara

[prod]
seven


;===============================================================================
; Web hosts
;===============================================================================

[hetzner]
seven

[home]
kara

