kara ansible_host=kara.djm.me ansible_user=ubuntu ansible_become=yes
#summer ansible_host=summer.djm.me ansible_user=root


; ENVIRONMENTS

[dev]
kara

[prod]
#summer


; WEB HOSTS

[hetzner]
#summer

[home]
kara

