- hosts: all
  roles:

    - role: provision-common
      tags: [common]

    - role: provision-dev
      tags: [dev]
      when: is_dev

    - role: provision-prod
      tags: [prod]
      when: is_prod
