- name: Reload Apache configuration
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Restart MariaDB
  ansible.builtin.systemd:
    name: mysql
    state: restarted
