- name: Reinitialise the Postfix SMTP relay authentication database
  ansible.builtin.command: postmap /etc/postfix/sasl_passwd

- name: Reinitialise the Postfix aliases database
  ansible.builtin.command: newaliases

- name: Reload Apache configuration
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Restart MariaDB
  ansible.builtin.systemd:
    name: mysql
    state: restarted

- name: Restart PHP 8.1 FPM
  ansible.builtin.systemd:
    name: php8.1-fpm
    state: restarted
    daemon_reload: yes

- name: Reload Postfix
  ansible.builtin.systemd:
    name: postfix
    state: reloaded

- name: Restart Unattended Upgrades download timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: restarted
    daemon_reload: yes

- name: Restart Unattended Upgrades upgrade timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: restarted
    daemon_reload: yes
