- name: Install Dotfiles in 'dave' account
  ansible.builtin.script: roles/provision-common/files/install-dotfiles.sh
  args:
    creates: /home/dave/.git
  vars:
    ansible_become: yes
    ansible_become_user: dave

- name: Install Dotfiles in root account
  ansible.builtin.script: roles/provision-common/files/install-dotfiles.sh
  args:
    creates: /root/.git
  vars:
    ansible_become: yes
    ansible_become_user: root
