- name: Add/update APT keys
  apt_key: '{{ item }}'
  loop:
    # Node.js (https://github.com/nodesource/distributions/blob/master/README.md#manual-installation)
    - url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      keyring: /etc/apt/keyrings/deb.nodesource.com.gpg
    # PHP PPA
    - keyserver: hkps://keyserver.ubuntu.com
      id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
      keyring: /etc/apt/keyrings/ppa.launchpad.net_ondrej_php.gpg
    # Yarn (https://classic.yarnpkg.com/en/docs/install/#debian-stable)
    - url: https://dl.yarnpkg.com/debian/pubkey.gpg
      keyring: /etc/apt/keyrings/dl.yarnpkg.com.gpg
  tags: [apt]

- name: Add custom APT repositories
  ansible.builtin.apt_repository:
    repo: deb [signed-by={{ item.keyring }}] {{ item.source }}
    mode: 0644
  loop:
    # Node.js (https://github.com/nodesource/distributions/blob/master/README.md#manual-installation)
    - source: https://deb.nodesource.com/node_18.x {{ ansible_facts.distribution_release }} main
      keyring: /etc/apt/keyrings/deb.nodesource.com.gpg
    # PHP PPA
    - source: http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_facts.distribution_release }} main
      keyring: /etc/apt/keyrings/ppa.launchpad.net_ondrej_php.gpg
    # Yarn (https://classic.yarnpkg.com/en/docs/install/#debian-stable)
    - source: http://dl.yarnpkg.com/debian/ stable main
      keyring: /etc/apt/keyrings/dl.yarnpkg.com.gpg
  tags: [apt]

- name: Install common APT packages
  ansible.builtin.apt:
    name:
      - acl # For Ansible - https://docs.ansible.com/ansible-core/2.12/user_guide/become.html#risks-of-becoming-an-unprivileged-user
      - anacron # Run daily cron tasks if missed
      - apache2
      - apache2-utils # Includes htpasswd
      - bat
      - bundler
      - chrony # NTP
      - dos2unix
      - ffmpeg # For Gallery
      - fzf
      - iotop
      - jq
      - libapache2-mod-fcgid
      - libapache2-mod-passenger
      - libmariadb-dev # For Redmine (mysql2 gem)
      - libffi-dev # For Node.js
      - libssl-dev # For Node.js
      - mailutils # 'mail' command
      - mariadb-client
      - mariadb-server
      - mlocate
      - moreutils # Includes sponge
      - ncdu
      - net-tools # Includes netstat
      - nodejs
      - p7zip-full
      - php-pear
      - php8.1-cli
      - php8.1-curl
      - php8.1-dev
      - php8.1-fpm
      - php8.1-gd # For Gallery
      - php8.1-mysql
      - php8.1-opcache
      - php8.1-readline
      - pv
      - python3-mysqldb # For Ansible - https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html#ansible-collections-community-mysql-mysql-user-module
      - python3-pip
      - rename
      - ruby
      - ruby-dev
      - snapd
      - tree
      - unattended-upgrades
      - whois
      - yarn
      - zip # Required by Composer
    state: present
    update_cache: yes
  tags: [apt]

- name: Install/upgrade Python packages
  ansible.builtin.pip:
    name:
      - httpie
      - thefuck
      - git+https://github.com/joh/when-changed#master
    state: latest
  tags: [pip]

- name: Install/upgrade Delta
  ansible.builtin.apt:
    # https://github.com/dandavison/delta/releases
    deb: https://github.com/dandavison/delta/releases/download/0.14.0/git-delta_0.14.0_amd64.deb
    state: present

- name: Install/upgrade duf
  ansible.builtin.apt:
    # https://github.com/muesli/duf/releases
    deb: https://github.com/muesli/duf/releases/download/v0.8.1/duf_0.8.1_linux_amd64.deb
    state: present

- name: Install Lazy Git
  ansible.builtin.shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/')
    curl -fsSL "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" \
      | tar zx -C /usr/local/bin/ lazygit
  args:
    creates: /usr/local/bin/lazygit

