- name: Add/update APT keys
  apt_key: '{{ item }}'
  loop:
    # PHP PPA
    - keyserver: hkps://keyserver.ubuntu.com
      id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
      keyring: /etc/apt/keyrings/ppa.launchpad.net_ondrej_php.gpg

- name: Add PHP PPA repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/ppa.launchpad.net_ondrej_php.gpg] http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_facts.distribution_release }} main
    mode: 0644

- name: Install common APT packages
  ansible.builtin.apt:
    name:
      - acl # For Ansible - https://docs.ansible.com/ansible-core/2.12/user_guide/become.html#risks-of-becoming-an-unprivileged-user
      - anacron # Run daily cron tasks if missed
      - apache2
      - apache2-utils # Includes htpasswd
      - bat
      - chrony # NTP
      - dos2unix
      - ffmpeg # For Gallery
      - fzf
      - iotop
      - jq
      - libapache2-mod-fcgid
      - mariadb-client
      - mariadb-server
      - php8.1-cli
      - php8.1-dev
      - php8.1-fpm
      - php8.1-gd # For Gallery
      - php8.1-mysql
      - php8.1-opcache
      - php8.1-readline
      - php-pear
      - mlocate
      - molly-guard # Prevent accidental shutdowns
      - moreutils # Includes sponge
      - ncdu
      - net-tools # Includes netstat
      - python3-mysqldb # For Ansible - https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html#ansible-collections-community-mysql-mysql-user-module
      - python3-pip
      - pv
      - rename
      - snapd
      - tree
      - unattended-upgrades
      - whois
      - zip # Required by Composer
    state: present
    update_cache: yes
  tags: [apt]

- name: Install/upgrade Delta
  ansible.builtin.apt:
    # https://github.com/dandavison/delta/releases
    deb: https://github.com/dandavison/delta/releases/download/0.14.0/git-delta_0.14.0_amd64.deb
    state: present

- name: Install/upgrade duf
  ansible.builtin.apt:
    # https://github.com/muesli/duf/releases
    deb: https://github.com/muesli/duf/releases/download/v0.8.1/duf_0.8.1_linux_amd64.deb
    state: present

- name: Install Lazy Git
  ansible.builtin.shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/')
    curl -fsSL "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" \
      | tar zx -C /usr/local/bin/ lazygit
    creates=/usr/local/bin/lazygit

- name: Install/upgrade Python packages
  ansible.builtin.pip:
    name:
      - httpie
      - thefuck
      - git+https://github.com/joh/when-changed#master
    state: latest
