- name: Configure Postfix
  ansible.builtin.template:
    src: mail/postfix-main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
  notify: Reload Postfix

- name: Configure Postfix SMTP relay authentication
  ansible.builtin.template:
    src: mail/postfix-sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: 0600
  notify: Reinitialise the Postfix SMTP relay authentication database

- name: Set root user email forwarding address
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: '^root:'
    line: 'root: d@djm.me'
  notify: Reinitialise the Postfix aliases database
