- ansible.builtin.import_tasks: hostname.yml
  tags: [hostname]

- ansible.builtin.import_tasks: timezone.yml
  tags: [timezone]

- ansible.builtin.import_tasks: locales.yml
  tags: [locales]

- ansible.builtin.import_tasks: install.yml
  tags: [install]

- ansible.builtin.import_tasks: postfix.yml
  tags: [postfix, mail]

- ansible.builtin.import_tasks: unattended-upgrades.yml
  tags: [unattended-upgrades]

- ansible.builtin.import_tasks: sudo.yml
  tags: [sudo]

- ansible.builtin.import_tasks: dave-user.yml
  tags: [dave-user]

- ansible.builtin.import_tasks: dotfiles.yml
  tags: [dotfiles]

- ansible.builtin.import_tasks: apache.yml
  tags: [apache]

- ansible.builtin.import_tasks: letsencrypt.yml
  tags: [letsencrypt]

- ansible.builtin.import_tasks: mariadb.yml
  tags: [mariadb, mysql]

- ansible.builtin.import_tasks: php.yml
  tags: [php]
